version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.23.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.node_modules
            - ~/.npm

      # - run: yarn test

      - run: yarn build
